### ISSUE TITLE
open in sublime in new window

### ISSUE THREAD

**Issue by tobsn** [deanishe/alfred-repos#10]
currently its opening within the same window thats open - would be nice to get the project in a fresh window. :)

**Comment by deanishe** [comment]
That's an issue with Sublime, tbh. All the workflow does is pass the directory path or URL to the application(s) you've specified.

Instead of using Sublime directly, I use a helper app that looks for a `.sublime-project` file in the directory, and if there is one, opens that with `subl` instead.
