### ISSUE TITLE
Error in workflow - No JSON object could be decoded

### ISSUE THREAD

**Issue by christopherdwhite** [deanishe/alfred-repos#11]
Hey, 

Repos looks awesome but unfortunately I seem to be getting an error.

![superlumic-config](https://cloud.githubusercontent.com/assets/1746405/18059905/7b2e8fe8-6dd8-11e6-9071-c24672cca077.png)

I'm not a JSON expert but I don't think there are errors in my configuration, here's what I have:

```json
{
  "app_1": "Finder",
  "app_2": "Atom",
  "app_3": "Sublime Text",
  "app_4": "Tower",
  "app_5": "HyperTerm",
  "app_6": ["Finder", "Atom", "Tower", "HyperTerm"],
  "global_exclude_patterns": [],
  "search_dirs": [
    {
      "path": "~/Source",
      "depth": 2
    },
  ]
}
```

Am I missing something? 

Note that I am running the Sierra beta so it may be incompatible but I doubt it in this context.

macOS Sierra 10.12 Beta (16A304a)
Alfred 3.1 [716]

**Comment by deanishe** [comment]
http://jsonlint.com

The problem is in `search_dirs`. There is a trailing comma here:

```
{
  "path": "~/Source",
   "depth": 2
 },
```

**Comment by christopherdwhite** [comment]
Dang, I can't believe I missed that. Thank you so much @deanishe, I really appreciate the help and the awesome workflow!
