### ISSUE TITLE
Initialising loop

### ISSUE THREAD

**Issue by iamso** [deanishe/alfred-repos#12]
Hi

A few weeks ago I got a new mac at work. I installed Alfred, installed this workflow and edited the config. But every time I want to run the workflow it says it's initialising. It has been like that from the beginning. I have tried uninstalling and reinstalling the workflow, deleting all the alfred db files and I tried with a fresh config file and added my directories. Nothing worked, it's still stuck on initialising.

It used to work on my old mac.

What could be the problem? And how can I make it work?

Thanks

**Comment by deanishe** [comment]
What does the log file/debugger say?

**Comment by deanishe** [comment]
Closing as abandoned.
