### ISSUE TITLE
Doesn't exclude a folder

### ISSUE THREAD

**Issue by nikitavoloboev** [deanishe/alfred-repos#16]
Here is my `settings.json` config:

```JSON
{
  "__workflow_last_version": "2.1.2",
  "app_alt": "iTerm",
  "app_cmd": "Finder",
  "app_shift": "Tower",
  "app_fn": "Safari",
  "app_default": "Visual Studio Code",
  "app_ctrl": "Sublime Text",
  "global_exclude_patterns": [],
  "search_dirs": [
    {
      "path": "~/src",
      "depth": 6,
      "excludes": [
          "play/*"
      ]
    },
    {
      "path": "~/go/src/github.com/nikitavoloboev",
      "depth": 3
    },
    {
      "path": "~/.dotfiles/"
    }
  ]
}
```

The issue is that the `excludes` block doesn't seem to work like I thought it would.

Here is contents of my `~/src` dir:
```Bash
~/src
❯ ls
Xcode		github		learning	play		scripts		uni
forks		ideas		ml		safari		testing
```

The play dir is in there. I made sure to force update with `reposupdate` and waited a bit too in case it cached those directories or something. But even then it shows me directories inside `play`. Not sure what I did wrong.

![2018-02-07 at 19 36](https://user-images.githubusercontent.com/6391776/35934556-32725d2e-0c3e-11e8-97c6-90e8d777084a.png)

Thank you for any help.

**Comment by deanishe** [comment]
Try `*/play/*`

**Comment by nikitavoloboev** [comment]
This worked. Thank you.
