### ISSUE TITLE
Where is the settings file located?

### ISSUE THREAD

**Issue by HendrikRoth** [deanishe/alfred-repos#3]
It seams, that i broke the settings.json file.
Where is it located?

**Comment by fdeneux** [comment]
Hello, where is the settings file located in Alfred 3? I've been having troubles after updating from v1.x.x to v2.1.2.

**Comment by deanishe** [comment]
Same place, but replace "Alfred 2" with "Alfred 3".

**Comment by fdeneux** [comment]
Thank you @deanishe, I thought they relocated everything to Alfred.alfredpreferences but I guess not the workflow data.
