### ISSUE TITLE
Watch for changes via FSEvents

### ISSUE THREAD

**Issue by lukescott** [deanishe/alfred-repos#7]
Awesome workflow btw! I was using s custom bash script with find and it was sometimes really slow. I switched to this workflow and it's awesome :+1:. Love the caching!

I was thinking about writing something like this, but I'm not as familiar with Python as I am with Go. One of the things I was looking at is FSEvents, which lets you watch a directory for changes recursively.

There is a library called [MacFSEvents](https://pypi.python.org/pypi/MacFSEvents) for Python that wraps FSEvents. You could use this to update the index immediately rather than having to poll every 3 hours.

**Comment by deanishe** [comment]
I've looked into FSEvents before. It's something I've wanted to try for some time, but I don't think it's a good match for the workflow, tbh. As a general rule, I don't like the idea of workflows running daemon processes, which I believe would be necessary to use FSEvents. It's complicated and wastes cycles if you're not actually using the workflow. This is the reason I also don't use a cron job/launch agent.

My understanding of FSEvents is that you watch, say, `~/Code`, and it fires an event whenever *anything* in that tree changes, which would be an awful lot of events, at least relative to the events the workflow is interested in (creation/deletion of files/directories called ".git").

That particular library is also a no-go, as it's a C extension, so it won't work on both Python 2.6 (Snow Leopard) and 2.7 (newer OSes).

The current method using `find` is inelegant and finicky, but it's the best of a bad lot, IMO. Things like `locate` (which I also tried) and FSEvents will also find all your submodules, which usually isn't what you want, and I found it much more work to exclude all that stuff in the configuration than the current whitelist-focussed method.
